---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Build
description: A build represents an individual build job for docker image
stability: prototype
strictProperties: true
type:
- object
definitions:
  identity:
    anyOf:
    - "$ref": "/schemata/build#/definitions/id"
  id:
    description: unique identifier of build
    readOnly: true
    format: uuid
    example: 01234567-89ab-cdef-0123-456789abcdef
    type:
    - string
  source_repo:
    description: source github source_repositry to build. It must includes Dockerfile
    required: true,
    example: "wantedly/risu"
    type:
    - string
  source_revision:
    description: git revision to use for build. (also you can use git tag/branch for this).
    required: true,
    example: "ada9ce1829fab49e605e5a563dbf91274f64e923"
    type:
    - string
  name:
    description: a repository name (and optionally a tag) to apply to the resulting image in case of success.
    required: true,
    example: "quay.io/wantedly/risu:latest"
    type:
    - string
  dockerfile:
    description: path within the build context to the Dockerfile
    example: "Dockerfile.dev"
    default: "Dockerfile"
    type:
    - string
  status:
    description: status of build. one of "failed" or "building" or "succeeded"
    readOnly: true
    example: "succeeded"
    type:
    - string
  created_at:
    description: when build was created
    readOnly: true
    format: date-time
    type:
    - string
  updated_at:
    description: when build was updated
    readOnly: true
    format: date-time
    type:
    - string
links:
- description: Create a new build.
  href: "/builds"
  method: POST
  rel: create
  schema:
    properties: {
      "source_repo": {
        "$ref": "/schemata/build#/definitions/source_repo"
      },
      "source_revision": {
        "$ref": "/schemata/build#/definitions/source_revision"
      },
      "name": {
        "$ref": "/schemata/build#/definitions/name"
      },
      "dockerfile": {
        "$ref": "/schemata/build#/definitions/dockerfile"
      },
    }
    type:
    - object
  title: Create
- description: Info for existing build.
  href: "/builds/{(%2Fschemata%2Fbuild%23%2Fdefinitions%2Fidentity)}"
  method: GET
  rel: self
  title: Info
- description: List existing builds.
  href: "/builds"
  method: GET
  rel: instances
  title: List
properties:
  id:
    "$ref": "/schemata/build#/definitions/id"
  source_repo:
    "$ref": "/schemata/build#/definitions/source_repo"
  source_revision:
    "$ref": "/schemata/build#/definitions/source_revision"
  name:
    "$ref": "/schemata/build#/definitions/name"
  dockerfile:
    "$ref": "/schemata/build#/definitions/dockerfile"
  status:
    "$ref": "/schemata/build#/definitions/status"
  created_at:
    "$ref": "/schemata/build#/definitions/created_at"
  updated_at:
    "$ref": "/schemata/build#/definitions/updated_at"
id: schemata/build
